# Generated by Django 5.0.6 on 2024-05-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vtso", "0002_company_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="Harbour",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=256, null=True)),
                ("max_berth_depth", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "harbour_master",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=256, null=True)),
                ("country", models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
    ]
