# Generated by Django 5.0.6 on 2024-05-25 11:46

import django.db.models.deletion
from django.db import migrations, models

import vtso.models


class Migration(migrations.Migration):

    dependencies = [
        ("vtso", "0004_alter_harbour_table_alter_person_table_ship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ship",
            name="year_built",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                validators=[vtso.models.validate_year_in_range],
            ),
        ),
        migrations.CreateModel(
            name="HarbourLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("entry_time", models.DateTimeField(blank=True, null=True)),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                (
                    "harbour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vtso.harbour"
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vtso.ship"
                    ),
                ),
            ],
            options={
                "db_table": "HABOUR_LOG",
            },
        ),
    ]
